### ISSUE TITLE
Support stale / consistent queries

### ISSUE THREAD

**Issue by jhmartin** [WeAreFarmGeek/diplomat#110]
https://www.consul.io/docs/agent/http.html under 'Consistency Modes'

**Comment by evan2645** [comment]
Beyond this? https://github.com/WeAreFarmGeek/diplomat/blob/master/lib/diplomat/kv.rb#L16

**Comment by taharah** [comment]
@jhmartin does what @evan2645 provide the functionality you were looking for?

**Comment by maxvt** [comment]
https://www.consul.io/docs/agent/http.html says "most read query endpoints support specifying consistency". At the very least, this option would be useful for service and health API endpoints, because for service discovery being consistent is often less important than getting at least some results right.

For more context, see https://stripe.com/blog/service-discovery-at-stripe

**Comment by kamaradclimber** [comment]
Any progress on that feature? Not being able to use stale makes every application based on diplomat unreliable when consul cluster does not have a leader.

**Comment by pierresouchay** [comment]
Please also consider ['leader'](https://github.com/hashicorp/consul/pull/4004/files#diff-03f1adb0cf098d94755af53cf0b484d6R404) consistency mode => which forces basic consistency over discovery endpoints

* `?stale` => allow to read from any consul server
* `?consistent` => strong consistency
* default => consistent (but can be changed on discovery endpoints, see [discovery_max_stale](https://www.consul.io/docs/agent/options.html#discovery_max_stale)
* [`?leader`](https://github.com/hashicorp/consul/pull/4004/files#diff-03f1adb0cf098d94755af53cf0b484d6R404) => new in 1.0.7, allow to use old consistent method for discovery endpoints

**Comment by pierresouchay** [comment]
Would you consider https://github.com/WeAreFarmGeek/diplomat/pull/165 ?

Kind regards

**Comment by pierresouchay** [comment]
Now available with the changes in 2.1.0
