### ISSUE TITLE
Randomize service results

### ISSUE THREAD

**Issue by jhmartin** [WeAreFarmGeek/diplomat#111]
Consul returns http service calls in a consistent order, when 'usually' one doesn't want all clients to use the same instance.  When requesting just one instance of a service, return a random instance from the list of results.

**Comment by pierresouchay** [comment]
@jhmartin do you still need this? What about having a helper to randomize results?

**Comment by jhmartin** [comment]
I don't need it myself, but my concern is people will expect a round-robin behavior from this and get something else.

**Comment by pierresouchay** [comment]
Closing it for now, feel free to re-open if it is a real need
