### ISSUE TITLE
Options for health endpoint are missing / incorrect 

### ISSUE THREAD

**Issue by defsprite** [WeAreFarmGeek/diplomat#113]
According to https://www.consul.io/docs/agent/http/health.html the possible parameters for `/v1/health/service/:service` are:

- `dc` (implemented correctly)
- `near` (missing)
- `passing` (implemented as `state`, which does not seem to work)

I am trying to filter only healthy nodes for a service, which does not seem to work without client-side post-processing. 

Am I missing something? Is this version specific?

**Comment by taharah** [comment]
I just saw this issue. I recently created a PR to fix another issue I found with the health endpoint that returns Hashes instead of OpenStructs as stated in the documentation. I'll add this to the PR as well.

**Comment by taharah** [comment]
This should be resolved via: [114](https://github.com/WeAreFarmGeek/diplomat/pull/114)

**Comment by taharah** [comment]
PR has been merged.

**Comment by defsprite** [comment]
This is great news! Thanks @taharah
