### ISSUE TITLE
Service lookup is not idiomatic ruby

### ISSUE THREAD

**Issue by sandstrom** [WeAreFarmGeek/diplomat#117]
Currently, a service lookup goes like this:

```ruby
mail_service = Diplomat::Service.get('mail')
mail_service.inspect # <OpenStruct Node="i-0c9693e4", Address="10.10.20.220", ServiceID="mail", ServiceName="mail", ServiceTags=[], ServiceAddress="", ServicePort=8080, ServiceEnableTagOverride=false, CreateIndex=4398409, ModifyIndex=4549606>

host, port = sage_service.Address, sage_service.ServicePort

```

This syntax is unlike anything else in ruby, where properties and methods are `snake_cased` and only classes are `CamelCased`.

One would expect something like this:

```ruby
mail_service = Diplomat::Service.get('mail')
mail_service.inspect # <OpenStruct node="i-0c9693e4", address="10.10.20.220", service_id="mail", service_name="mail", service_tags=[], service_address="", service_port=8080, service_enable_tag_override=false, create_index=4398409, modify_index=4549606>

host, port = sage_service.address, sage_service.service_port

```

Overall Diplomat is excellent! ⛵️  

But this part could use some adjustments to make it align with all of Rubys standard-library plus basically all other gems.

***

*A related method naming issue aside: since `Service.get` is called it feels a bit tautological to then call the method `service_port` instead of just `port` (same for `service_tags`, `service_name`, etc).*

**Comment by taharah** [comment]
The reason the syntax is like that is because it matches what is used by the API, which is written in Go. Some re-work and most likely a custom object would need to be developed in order to make the return values more closely match Ruby syntax.

**Comment by taharah** [comment]
I'm starting to plan out the next major release and I'd like to create a custom object for the API responses and requests, which would resolve this issue.

**Comment by sandstrom** [comment]
@taharah Sounds great! 🐥 👍  There is also https://github.com/WeAreFarmGeek/diplomat/issues/87 (which I'm sure you know about already)

If there is a draft or RFC outlining the upcoming changes / new API surface I'm happy to provide thoughts and comments.

Generally, I'd say the RFC format is very good for API surface changes. Writing it out before coding can save a lot of time and also helps oneself to iteratively improve the design before committing.

**Comment by prikha** [comment]
Vote for this one! @taharah @sandstrom  Ping me if help needed

**Comment by pierresouchay** [comment]
This issue is old and no contribution nor comment on it. Closing it.
As explained this is linked to Consul attributes directly, changing it would break ascending compatibility. Feel free to provide a PR (and re-open this issue) if you want to fix it
