### ISSUE TITLE
Kv.get /w recurse: true is not consistent

### ISSUE THREAD

**Issue by t3hk0d3** [WeAreFarmGeek/diplomat#119]
`Kv.get` with recurse: true is not consistent if there is only single key were returned.

I am expecting array of key/values, but if there is only single key it would return just its value.

```ruby
Diplomat::Kv.put('hello/world', 'test')

Diplomat::Kv.get('hello', recurse: true)
# current:
# => 'test'
# expected
# => [{ key: 'hello/world', value: 'test'}]
```

Current workaround is specifying `decode_values: true`:
```ruby
Diplomat::Kv.get('hello', recurse: true, decode_values: true)
# => {[ 'Key' => 'hello/world', 'Value' => 'test', ... }]

```

But there is no way to make ``convert_to_hash`` to work with single key atm.

**Comment by taharah** [comment]
PR has been created to resolve this bug. Please review it if you are able to.

**Comment by ghostsquad** [comment]
along these lines, `convert_to_hash` straight up fails when the value is a simple string.
```
Diplomat::Kv.get("/foo/bar/baz", recurse: true, convert_to_hash: true)
NoMethodError: undefined method `each' for "asdfasd":String
```

I expected to either get a hash or a string based on the value. The workaround is not very performant, as it requires me to first try with `convert_to_hash: true`, and if that fails, call the method again without that parameter.

**Comment by t3hk0d3** [comment]
@taharah 
Actually i think it should be a different method for recursive get:
```ruby
Diplomat::Kv.list('foo/bar/baz') # same as get + recurse: true
Diplomat::Kv.tree('foo/bar') # same as get + recurse: true + convert_to_hash: true
```
