### ISSUE TITLE
Unable to compile the json gem on production machines

### ISSUE THREAD

**Issue by scottybrisbane** [WeAreFarmGeek/diplomat#144]
I am wanting to use this library with Puppet, but we don't want to have to compile native extensions on our production machines before puppet can run. This is currently required for us to use diplomat, because of the dependency on the `json` gem.

Would it be possible to move to using `json_pure` instead?

**Comment by taharah** [comment]
This is something I can look into. My company is a large Chef consumer, so I've never ran into this issue before, and I believe JSON is installed by default with newer versions of Ruby (>= 2.3).

**Comment by EugenMayer** [comment]
even if you use Chef (chef user myself), this is an issue on all boxes, all docker containers and is usually creating a huge overkill.

json_pure works pretty solid in those cases
