### ISSUE TITLE
Diplomat needs a client

### ISSUE THREAD

**Issue by ghostsquad** [WeAreFarmGeek/diplomat#167]
## Problem Statement

Although I've seen in done time and time again in other ruby libraries, having a global configuration makes it really hard to use dependency injection.

The main problem though (the reason for this issue), is that I need to be able to talk to multiple different consul API endpoints, and right now the only real way to do that is something like the following.

```
def get(url, key)
   Diplomat.configure do |config|
     config.url = url
   end
   Diplomat::Kv.get(key)
end
```

You can imagine, there's a slew of race-condition like bugs that exist in code written this way.

## A Reasonable Proposal

```
client = Diplomat.new(config)
client.get("fookey")
```

**Comment by ghostsquad** [comment]
I see there's a PR that seems related to this issue: #163

**Comment by pierresouchay** [comment]
@ghostsquad Fully agree on that :-)
I actually to plan to review all the pending review and try simplifying the APIs at the same time to always allow configuration per request of global parameters. #163 has been proposed by one of my colleagues, so I can ensure you it will be quickly merged and release published.

Thank you for your patience

Kind regards

**Comment by pierresouchay** [comment]
#163 has been merged, @ghostsquad  Ok for you?
