### ISSUE TITLE
Upload 2.0.3 to Rubygems.org

### ISSUE THREAD

**Issue by c2nes** [WeAreFarmGeek/diplomat#168]
I noticed that version 2.0.3 has been tagged, but that 2.0.2 is the latest version on RubyGems.org. Would it be possible to get 2.0.3 uploaded to RubyGems.org as well?

Thanks!

**Comment by johnhamelink** [comment]
Yes! I plan on doing some housekeeping in this repo over this weekend, including making sure rubygems is up to date.

**Comment by thumbnail** [comment]
I'm sorry to bump, but is there any update on this?

**Comment by pellepelster** [comment]
Any news on the update? I am kind of blocked by missing changes that ought to be released with 2.0.3.

/cheers

**Comment by kamaradclimber** [comment]
@pierresouchay could you have a look and release the latest version this gem please?

**Comment by pierresouchay** [comment]
DONE for 2.0.4, now automatic push of releases from travis when using a tag
