### ISSUE TITLE
Not working with ruby 2.5

### ISSUE THREAD

**Issue by EugenMayer** [WeAreFarmGeek/diplomat#171]
When working with 2.5 ( e.g. ruby:2.5-slim-stretch official docker image )
One gets a 301 moved permanently on each KV access

```
/usr/local/bundle/gems/diplomat-2.0.2/lib/diplomat/kv.rb:88:in `get': status 301: <a href="/v1/kv/tiller/globals/all?dc=stable&amp;keys">Moved Permanently</a>. (Diplomat::UnknownStatus)
```

**Comment by pierresouchay** [comment]
@EugenMayer @rockpapergoat How?

Can you please try this?

Create file test.rb (executable):
```
#!/usr/bin/env ruby
require 'diplomat'

raise "USAGE: <KV_PATH_TO_GET>" unless ARGV.count > 0

Diplomat.configure do |config|
  config.url = ENV['CONSUL_HTTP_ADDR'] || "http://localhost:8500"
end
foo = Diplomat::Kv.get(ARGV[0])
puts "#{ARGV[0]}: #{foo}"
```
Run it with `CONSUL_HTTP_ADDR=http://localhost:8500 ./test.rb PATH_TO_KV`

(You can replace CONSUL_HTTP_ADDR with the value of the consul agent you are targeting)

On my side, with ruby-2.5.3, working quite well...
What OS? Docker/Alpine?

**Comment by rockpapergoat** [comment]
sorry for the delay. my issue was not specifying the full path to the key. ubuntu 16.04/ruby 2.5.1 worked/works fine, as far as i can tell.

**Comment by EugenMayer** [comment]
@pierresouchay its all up there 

`When working with 2.5 ( e.g. ruby:2.5-slim-stretch official docker image )`

**Comment by pierresouchay** [comment]
@EugenMayer So, I suspect you are using :
```
Diplomat::Kv.get('/tiller/globals/all', ...)
```
right?

Using:
```
Diplomat::Kv.get('tiller/globals/all', ...)
```
Would probably fix your issue (note that I removed the first '/')

@EugenMayer Can you confirm this?

**Comment by EugenMayer** [comment]
Well @pierresouchay i am not sure you are right about that, since in this case, the request is wrapped by https://github.com/markround/tiller - but i remember having issues with my direct ruby diplomat implementation.

Still looking at the error and the cause it seem viable - still why did this happen with ruby 2.5 but not with < 2.5? Does not make sense this redirect is only triggered then. Probably in 2.5 the redirect is not followed automatically, similar to curls `-L` ?

Thanks

**Comment by pierresouchay** [comment]
@EugenMayer might be. I definitely have a 302 if using /anykey for a KV.get(). This is a problem anyway, because I am not sure of behavior if using put for instance.

There might be a change in ruby to default following 302 from 2.4 to 2.5, but we might simply fix this globally in diplomat if self to avoid this behavior
