### ISSUE TITLE
use json_pure?

### ISSUE THREAD

**Issue by bobchaos** [WeAreFarmGeek/diplomat#177]
a few hours ago a new version of the `json` rubygem went up on rubygems.org, and suddenly I need gcc to install diplomat. I'm wondering if you'd consider pinning the gem version to 2.1.0 (I note it's the only unpinned dependencyyou have) or depending on `json_pure`instead of `json` as described here: http://flori.github.io/json/ in order to restore the previous behavior. Thanks!

**Comment by pierresouchay** [comment]
@bobchaos Are you using ruby version 1.9.3 ?

This dependency is required only for very old ruby versions...

You can do a PR to enforce it, I'll review it quickly

**Comment by pierresouchay** [comment]
Fixed by https://github.com/WeAreFarmGeek/diplomat/commit/f45b152f6b44674b6f17b17c78107a88758de82d

**Comment by bobchaos** [comment]
using v2.5, but I notice you're comparing the version as a string, may be better as a `Gem::Version` either way thanks for the change, solved my issue nicely
