### ISSUE TITLE
Support Consul 1.4.0+ ACL system

### ISSUE THREAD

**Issue by scalp42** [WeAreFarmGeek/diplomat#193]
Current Diplomat only supports legacy API endpoints:

```
PUT /acl/create - Create Legacy Token
PUT /acl/update - Update Legacy Token
PUT /acl/destroy/:uuid - Delete Legacy Token
GET /acl/info/:uuid - Read Legacy Token
PUT /acl/clone/:uuid - Clone Legacy Token
GET /acl/list - List Legacy Tokens
```

The new system doesn't allow naming the token itself, only the description. A new `AccessorID` gets created instead and acts as the `ID` in the legacy system.

I'm going to start working on a PR.

**Comment by pierresouchay** [comment]
@scalp42 Thank you for the PR!

**Comment by scalp42** [comment]
@pierresouchay Unfortunately/fortunately with `1.5.0`, we'll have to change the gem again, see https://github.com/hashicorp/consul/issues/4977#issuecomment-489329565
