### ISSUE TITLE
Add support for Consul 1.5.x ACL tokens

### ISSUE THREAD

**Issue by scalp42** [WeAreFarmGeek/diplomat#195]
With the release of Consul 1.5.x (https://github.com/hashicorp/consul/blob/master/CHANGELOG.md#150-may-08-2019), we can now pass a named token which should help with Chef.

Going to work on it @pierresouchay

**Comment by pierresouchay** [comment]
@scalp42 Do you need something else ?
Can we close it, you probably need a release to use it properly?

**Comment by scalp42** [comment]
@pierresouchay correct can be closed. Still working on Chef support for it.
