### ISSUE TITLE
404 and Exception if key is missing

### ISSUE THREAD

**Issue by mcansky** [WeAreFarmGeek/diplomat#20]
At the moment a ```Diplomat.get('foo')``` raise an exception if the 'foo' key does not exist in the key/value store.

This looks like an odd behaviour as I was expecting a ```nil``` value (as would Redis or Memcached do for example).

I understand #16 do some work around this very thing but does not seem to change the end behavior. Is there any reason why the exception is raised rather than returning a nil value ?

**Comment by mcansky** [comment]
see https://github.com/WeAreFarmGeek/diplomat/pull/22

**Comment by johnhamelink** [comment]
see #31
