### ISSUE TITLE
Unable to use multiple tags when querying for services

### ISSUE THREAD

**Issue by jebentier** [WeAreFarmGeek/diplomat#212]
Right now for example `Diplomat::Health.service` allows the passing of a `tag` option to filter the results from Consul. But this only accepts a single string today.  It would be nice to be able to pass this an array of strings so that you can pass multiple tags that are all required to exist on the registered service for it to be returned by Consul.  [Consul's API](https://www.consul.io/api-docs/health#tag) supports this through specifying the `tag` query parameter multiple times.

If others feel like this is worth while, I'd be more than happy to put together a PR for the enhancement.

**Comment by pierresouchay** [comment]
@jebentier Sure, feel free to submit a PR!

**Comment by jebentier** [comment]
@pierresouchay That is great to hear, I've gone ahead and created PR #213
