### ISSUE TITLE
Bump faraday requirement

### ISSUE THREAD

**Issue by Sapr0** [WeAreFarmGeek/diplomat#214]
Newer chef-client (16.9.29+) come embedded with `faraday 1.3.0` which breaks current `diplomat` gem due to the `faraday < 1.1.0` requirement and makes it unable to use during a chef-run.

Can you release `diplomat 3.0` major version with a higher faraday requirement and implicitly higher ruby requirement.
Whoever needs an old ruby can just pin the gem to the 2.4.4 version, after all that's why we use SemVer for versioning.

Also Ruby below 2.5 is EOL, yet an other reason to keep up with the newer versions of ruby/faraday

**Comment by pierresouchay** [comment]
@Sapr0 Sure, can you propose a PR for that (I mean with the correct bumps and updated GEMs) ?
