### ISSUE TITLE
Broken link to API documentation

### ISSUE THREAD

**Issue by bustikiller** [WeAreFarmGeek/diplomat#218]
The link to the rubydoc documentation seems to be broken. It used to work some days ago:

https://rubydoc.info/github/WeAreFarmGeek/diplomat

> We haven't generated any docs for WeAreFarmGeek/diplomat. You can add the project yourself by entering the GitHub project information below. You can also see a list of available projects here.

**Comment by pierresouchay** [comment]
Hello @bustikiller ... the doc seems to work on my machine: https://rubydoc.info/github/WeAreFarmGeek/diplomat

Maybe someone did re-generated it, IIRC, there are path in https://rubydoc.info to regenerate it... seems ok anyway, feel-free to re-open it if it happens again

**Comment by bustikiller** [comment]
> Hello @bustikiller ... the doc seems to work on my machine: https://rubydoc.info/github/WeAreFarmGeek/diplomat
> 
> Maybe someone did re-generated it, IIRC, there are path in https://rubydoc.info to regenerate it... seems ok anyway, feel-free to re-open it if it happens again

Good morning!! I did re-generate it in an attempt to fix it - and it worked. If I see that happening again, I'll do it without opening a ticket. Thanks!

**Comment by pierresouchay** [comment]
When I'll find some time I'll try to add a scheduled action to regenerate the doc periodically
