### ISSUE TITLE
Calls to Diplomat::Service fail with uninitialized constant Diplomat::Service::OpenStruct

### ISSUE THREAD

**Issue by thedebugger** [WeAreFarmGeek/diplomat#26]
I think we need to add `require 'ostruct'`. Weird that no one ran into this issue. Thoughts?

**Comment by johnhamelink** [comment]
Hey @thedebugger thanks for this! I will look into it on the weekend and see why the tests aren't failing before we try and fix this.

**Comment by johnhamelink** [comment]
@thedebugger it's strange that I'm not getting any error when I'm running the specs, and both the code and the specs use openstruct quite regularly.

I also tried querying for a service from irb:

```bash
    consul agent -bootstrap -server -data-dir=/tmp
```
```bash
    irb
    require_relative 'lib/diplomat.rb'
    Diplomat::Service.get 'consul'
    => #<OpenStruct Node="Johns-MacBook-Pro-3.local", Address="10.133.10.100", ServiceID="consul", ServiceName="consul", ServiceTags=[], ServicePort=8300>
```

**Comment by thedebugger** [comment]
@johnhamelink, rspecs works fine. And, what gems did you load in 'irb'? I think you will be able to replicate the problem when the application (and it dependencies) doesn't require 'ostruct'. To workaround, I added `require 'ostruct'` in my application and calls work fine.

**Comment by johnhamelink** [comment]
@thedebugger other than cd'ing into the diplomat source, I'm not doing anything other than what I described in the comment above... I will explicitly include ostruct if this solves your issue, but I'm still not 100% on why its not happening for anyone else...

**Comment by thedebugger** [comment]
hmm..let me see if I can replicate it.

**Comment by johnhamelink** [comment]
Thanks @thedebugger :)

**Comment by johnhamelink** [comment]
How did you get on @thedebugger ?

**Comment by thedebugger** [comment]
Didn't get a chance to reproduce it, yet.



—

**Comment by johnhamelink** [comment]
Cool, let us know when you get round to it :+1:

**Comment by johnhamelink** [comment]
@thedebugger I'm going to close this issue for now until you can get back to us! Thanks :smile:

**Comment by LoganBarnett** [comment]
I ran into this issue with a non-trivial codebase.  I tried to reproduce it with something really minimal from within Diplomat itself:

```
$ bundle exec ruby -e 'require "diplomat"; p(OpenStruct.new({}))'
#<OpenStruct>
```

But clearly it works.

A minimal negative test shows that generally, one must `require 'ostruct'` to pull in `OpenStruct`:

```
$ ruby -e 'p(OpenStruct.new({}))'  
-e:1:in `<main>': uninitialized constant OpenStruct (NameError)
```

This makes me think some dependency is present in some circumstances is not present in others, but it's puzzling as to what that difference could be.  If Diplomat needs `OpenStruct`, I would think it would require the file regardless of what other dependencies might be doing.  This way if the dependencies no longer need `OpenStruct` (maybe they switched to a `ShinyNewStruct` :D ), Diplomat would continue as if nothing happened.  It would make us resilient against whatever circumstance is somes-requiring the file now.  I'm not trying to be pushy, but that's my pitch :)

Would you be amenable to a PR for this?  I see the value in making sure the tests catch the error but I'm not sure what's available to us to catch this in Ruby.

Regardless, I'll keep an eye out for what the difference might be when we run into this.
