### ISSUE TITLE
Faraday gem breaks SSL connections on 0.6.1

### ISSUE THREAD

**Issue by guymaliar** [WeAreFarmGeek/diplomat#27]
Hey guys, first I got to say that it's a great gem!
Unfortunately I found a bug that I can not pinpoint exactly what causes it, in my opinion it's related to Faraday but I couldn't find the commit that updated the Faraday gem.

What basically happens is that when I'm using version 0.5.1 I am able to use Diplomat with a middleware to talk to consul over SSL but with 0.6.1 I can not.

I'm using a self-signed ssl using a CA I created, used this tutorial to get it running, 
https://www.digitalocean.com/community/tutorials/how-to-secure-consul-with-tls-encryption-on-ubuntu-14-04

Steps to reproduce:

```json
# config.json
{
  "server": true,
  "ports": {
    "dns":  -1,
    "https": 8500,
    "http": -1
  },
  "encrypt": "NH4Ykhc4aqzdsSO8Rduchg==",
  "ca_file": "/src/research/diplomat/ca.cert",
  "cert_file": "/src/research/diplomat/consul.cert",
  "key_file": "/src/research/diplomat/consul.key",
  "verify_incoming": true,
  "verify_outgoing": true
}
```
 
```ruby
# test.rb
require 'rubygems'
require 'diplomat'

class DiplomatSSLMiddleware
  def initialize(app)
    @app = app
  end

  def call(env)
    env.ssl = {
      ca_file:     "/src/research/diplomat/ca.cert",
      client_cert: OpenSSL::X509::Certificate.new(File.read("/src/research/diplomat/consul.cert")),
      client_key:  OpenSSL::PKey::RSA.new(File.read("/src/research/diplomat/consul.key"))
    }

    @app.call(env)
  end
end

Diplomat.configure do |config|
  config.url        = "https://local.example.com:8500"
  config.middleware = DiplomatSSLMiddleware
end

Diplomat.get('test')
```

I created a SSL certificate for `local.exampe.com` and edited my local `/etc/hosts` to pinpoint it to localhost.

Running in a terminal window the following command to have a consul server running
`consul agent -data-dir=/src/research/diplomat -server -bootstrap -config-file=/src/research/diplomat/config.json`

Running `bundle exec ruby test.rb`

On `0.6.1`:

`SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)`

On `0.5.1`:
`the server responded with status 404 (Faraday::ResourceNotFound)`

* This is okay because I haven't set the key

**Comment by johnhamelink** [comment]
Hey there, thanks for this detailed report! It's a holiday today here in Scotland so I'm planning on sorting all of the outstanding issues and releasing a new version today.

Thanks for using diplomat!
JH

**Comment by johnhamelink** [comment]
For reference, here's a comparison between 0.5.1 and 0.6.1:

https://github.com/WeAreFarmGeek/diplomat/compare/c77985b96b641843f8107f0ae018af985b2642f9...6171639aff01cf35bd36e4dba81b74f888b3adba

**Comment by guymaliar** [comment]
I looked at the comparison when I was investigating but I didn't thoroughly go over it, it seems that this might be the first place to look for changes, diplomat/lib/diplomat/rest_client.rb

**Comment by johnhamelink** [comment]
@guymaliar have you tried adding the ca_path to the faraday config? Check here under Ubuntu: https://github.com/lostisland/faraday/wiki/Setting-up-SSL-certificates

If that doesn't work, can you try removing "faraday.adapter  Faraday.default_adapter" and running again? I'd do that but I'm on a mac right now with limited battery :smile:

**Comment by guymaliar** [comment]
:+1: I will have a go at both, will take me an hour or so though

**Comment by johnhamelink** [comment]
Cool, let me know how it goes either way - we'll get to the bottom of it :smile:

**Comment by guymaliar** [comment]
@johnhamelink actually it was faster than I thought, 
I commented out the `faraday.adapter Faraday.default_adapter` and it now returns `/src/research/diplomat/gem/lib/diplomat/kv.rb:60:in `get': status  (Diplomat::UnknownStatus)`

This looks the error message that should be returned.

Thoughts?

**Comment by johnhamelink** [comment]
Hey @guymaliar - how did you get on before? Did you manage to find a fix?

**Comment by guymaliar** [comment]
Hey guy, sorry I was on vacation, yes I managed to find a fix, removing the `faraday.adapter  Faraday.default_adapter` solved it.
I will send a pull request this week.

**Comment by johnhamelink** [comment]
Thanks @guymaliar :smile:

**Comment by johnhamelink** [comment]
@guymaliar I'm going to close this ticket for now, if you get time to submit a PR, please do :smile:

**Comment by guymaliar** [comment]
I will do it as soon as possible


—
