### ISSUE TITLE
v0.7.0 breaks Diplomat::Service.get(...)

### ISSUE THREAD

**Issue by jdrago999** [WeAreFarmGeek/diplomat#29]
Hi -

Starting with v0.7.0, the following breaks:

    require 'diplomat'
    Diplomat::Service.get('mysql').Address

You get the following error:

    ArgumentError: wrong number of arguments (0 for 1..4)
	   from /var/lib/gems/2.0.0/gems/diplomat-0.7.0/lib/diplomat/service.rb:13:in `get'
	    from /var/lib/gems/2.0.0/gems/diplomat-0.7.0/lib/diplomat/service.rb:47:in `get'

After downgrading to v0.6.1 the error disappeared.

**Comment by johnhamelink** [comment]
Hey @jdrago999 thanks for this.

You were right in your comment that those lines are the issue. The next release I make will fix this for you. I'll let you know when that release happens (today).

**Comment by johnhamelink** [comment]
[Released fix as 0.8.2](https://rubygems.org/gems/diplomat/versions/0.8.2)
