### ISSUE TITLE
Diplomat::Kv.get("unexistent_key", nil, :wait, :wait) raises an error when key does not exist

### ISSUE THREAD

**Issue by mikeys** [WeAreFarmGeek/diplomat#32]
Trying to fetch a non existent key from Consul's Key/Value store using the following:
```ruby
Diplomat::Kv.get("unexistent_key", nil, :wait, :wait)
```
Raises the following error:
`Faraday::ResourceNotFound: the server responded with status 404`

From the `Diplomat::Kv.get` documentation:
`@param not_found [Symbol] behaviour if the key doesn't exist;
    #   :reject with exception, :return degenerate value, or :wait for it to appear`

The behaviour should've been to keep blocking until the key exists.
Checking out the code, it seems like the problem originates from `Diplomat::RestClient#start_connection` (`lib/diplomat/rest_client.rb`):

```ruby
    def start_connection api_connection=nil
      @conn = build_connection(api_connection)
      @conn_no_err = build_connection(api_connection, true)
    end

    def build_connection(api_connection, raise_error=false)
```
`@conn_no_error` is being set to a Faraday client which DOES raise an error (notice the second argument which is set to `true` for `build_connection`) as opposed to `@conn`.

This is directly connected to:
`lib/diplomat/kv.rb`
```ruby
    def get key, options=nil, not_found=:reject, found=:return
      @key = key
      @options = options

      url = ["/v1/kv/#{@key}"]
      url += check_acl_token
      url += use_consistency(@options)

      # 404s OK using this connection
      raw = @conn_no_err.get concat_url url  # <= This statement raises the error
      if raw.status == 404
```

`@conn_no_err.get concat_url url` in the above raises the error since the Faraday client is set to raise errors.

**Comment by johnhamelink** [comment]
Thanks @mikeys - This was due to a refactoring I did yesterday to clean up some duplicated code!
