### ISSUE TITLE
Feature: allow to specify an 'index' on Diplomat::Kv.get

### ISSUE THREAD

**Issue by mikeys** [WeAreFarmGeek/diplomat#33]
Current `Diplomat::Kv.get` implementation does not allow to specify an `?index` param for fetching a key value if `index`'s value is smaller than the current key's `ModifyIndex` and "wait" (block) if it equals to it.
This is extremely useful for implementing a `watch` like functionality which avoids polling.

**Comment by johnhamelink** [comment]
Hey @mikeys,

This sounds like a cool addition. If you'd like to submit a PR, I'll happily consider :smile: 

JH
