### ISSUE TITLE
performace issue

### ISSUE THREAD

**Issue by jeffreyji666** [WeAreFarmGeek/diplomat#38]
I read the service.rb code, It seems that It does send http request to get server list every time

>> foo_service = Diplomat::Service.get('foo')

is invoked.

If I have a application with high traffic. does it will cause high pressure to consul cluster?

why don't cache the service url and its server list and start a daemon thread to update it?

**Comment by warmfusion** [comment]
Caching the values seems counter productive to the premise of Consul - You always want to have the authoritative state of a given key.

This being said, it may be possible to register a watch on a given tree, then cache any values within that sub-tree, expiring the cache if any key/value pairs are updated.

**Comment by jeffreyji666** [comment]
How about network accident happened when you sending http request to consul cluster?

**Comment by johnhamelink** [comment]
I'm not convinced watching the tree should be Diplomat's responsibilty - perhaps that could be some form of middleware for Diplomat? What do you think?

**Comment by johnhamelink** [comment]
Any further thoughts @warmfusion @jeffreyji666 ?

**Comment by jeffreyji666** [comment]
@johnhamelink  I use consul-template to replace this. more simple and robust.

**Comment by johnhamelink** [comment]
@jeffreyji666 Yep, to me that seems like a more sensible way to approach this issue. I'm closing this for now but if anyone has any other opinions please re-open this issue.
