### ISSUE TITLE
Error in session renew

### ISSUE THREAD

**Issue by rubiyz** [WeAreFarmGeek/diplomat#43]
The session can't be renewed. I looks like a typo on line 47 of session.rb.

Currently:
req.url = "/v1/session/renew/#{id}"

and should be:
req.url "/v1/session/renew/#{id}"

**Comment by johnhamelink** [comment]
Thanks for this, I'll look into it over this weekend.

**Comment by scalp42** [comment]
@johnhamelink any chance to fix it?

**Comment by boldfield** [comment]
Any chance to get the fix for this bug merged?

**Comment by johnhamelink** [comment]
I'm sorry guys I've been off the ball. I'm going to go through all of the outstanding issues on Consul now and get a new version out tonight :smile:

**Comment by scalp42** [comment]
Thanks @johnhamelink much appreciated

**Comment by johnhamelink** [comment]
Released in [0.13.0](https://rubygems.org/gems/diplomat/versions/0.13.0)
