### ISSUE TITLE
Feature: Service rotation

### ISSUE THREAD

**Issue by jtmarmon** [WeAreFarmGeek/diplomat#66]
In the same way consul DNS round robins services by IP address, it would be nice if diplomat would rotate all the available services for one service name (in this case, round robining w/ both IP and port rather than just  IP as consul's DNS works).

`Diplomat::Service.next('myservice')`

**Comment by johnhamelink** [comment]
That's a nice idea, but I think it's beyond the scope of the gem. Perhaps create a gem that complements diplomat by doing this? :smile: If you do that, you can submit a PR for the documentation which advertises your project.
