### ISSUE TITLE
please consider my enhancements for inclusion in your next gem version

### ISSUE THREAD

**Issue by cixelsyd** [WeAreFarmGeek/diplomat#7]
Hello John!  Thanks so much for your nicely done diplomat gem.  I've begun using it, along with consul and consul-template, and am very happy.  I wrote a new class, and a few new methods, that I'd like you to review for inclusion.  Sorry - my workstation is old, so I'm not setup to do pull requests, and haven't begun writing tests yet... that's the next hurdle I hope to attack shortly.

In the meantime, you can find my proposed files here:

http://speak.smashrun.com/assets/images/dip.tgz

I tried to keep your general sense of things.  You'll immediately see the new "key_exist" method, and the new "Agent" class, which I added due to the /v1/agent/ API structure.

let me know what you think!  Thanks again.

Steve
@cixelsyd

**Comment by johnhamelink** [comment]
Marking this as closed due to inactivity.
