### ISSUE TITLE
Add ModifyIndex & X-Consul-Index to all responses

### ISSUE THREAD

**Issue by johnhamelink** [WeAreFarmGeek/diplomat#8]
@cablehead (who is the author of [python-consul](https://github.com/cablehead/python-consul/)) mentioned on twitter that adding ModifyIndex & X-Consul-Index should be considered.

But first we need to decide how best to add this functionality in without breaking things too much.

@cablehead - any comments? :smile:

**Comment by galthaus** [comment]
How about this?

Get signature:
get(key, scope=:first, options={})
Input:
 options[:index] = string
 options[:wait] = string time component
Return
 options[:index] is modified on return to be the returned index.

This keeps get happy, doesn't change too much code, gives access to all values over time.  The options seems to be the ruby-ish standard way to pass in info and deal with expansion.  We could move in scope, but that would break existing things.

If you don't like the writing into an input focused structure, we could add a meta hash to return the requests meta data.  Put index, last-contact, ...

I working on this now.  I don't really care which I just need long polling.  :-)

**Comment by johnhamelink** [comment]
@galthaus looks nice :+1: 

Looking forward to seeing that PR!

**Comment by johnhamelink** [comment]
Solved thanks to #11

**Comment by johnhamelink** [comment]
Released in version 0.2.2: https://rubygems.org/gems/diplomat/versions/0.2.2
