### ISSUE TITLE
Keep a Changelog

### ISSUE THREAD

**Issue by sandstrom** [WeAreFarmGeek/diplomat#85]
Would be awesome if you'd like to add a change log:
http://keepachangelog.com/

Just tried out Diplomat, it's awesome! Also a big fan of the photos! On top of everything else I noticed @PeterFCaswell have an excellent taste in avatar photos 😄

**Comment by johnhamelink** [comment]
@sandstrom I know, you're right we really should be keeping track of the changes we're making. I will add a changelog file and write a contributing guide to the project, so that contributors will know how to add to the changelog.

Thanks for flagging this!
