### ISSUE TITLE
Inconsistent handling of 403 responses

### ISSUE THREAD

**Issue by pmenglund** [WeAreFarmGeek/diplomat#89]
When you have a consul ACL in place, the exceptions your get from diplomat are inconsistent:

E.g. `Diplomat::Acl.list` raises

    Diplomat::UnknownStatus: status 403

while `Diplomat::Acl.create({})` raises

    Faraday::ClientError: the server responded with status 403

which makes it messy to catch the exceptions and determine if authentication is needed.

**Comment by johnhamelink** [comment]
@pmenglund Thanks for this issue. We simply need to check to see what the correct response code is, and if it's not the correct one, respond with `Diplomat::UnknownStatus` as with the list function.

**Comment by johnhamelink** [comment]
Fixed in https://github.com/WeAreFarmGeek/diplomat/commit/492596ea106f69ca87608e67ff98d5dc68e3f7ac

**Comment by johnhamelink** [comment]
Released in [0.19.0](https://rubygems.org/gems/diplomat/versions/0.19.0)
